### ISSUE TITLE
Can not read property of add

### ISSUE THREAD

**Issue by DBlaNQ** [appellation/discord.js-music#1]
(node:8904) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'add' of undefined
(node:8904) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I don't know what's the problem

EDIT:
Found out what the error was about

**Comment by appellation** [comment]
re-open if you haven't actually solved the issue

**Comment by SkwalExe** [comment]
I hate people who says "I found out what the problem was" without giving the answer lmao
